<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ueg-proto/laravel-error-reporter/error.proto

namespace UegProto\LaravelErrorReporter\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>uegProto.laravelErrorReporter.api.ReportErrorRequest</code>
 */
class ReportErrorRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.uegProto.laravelErrorReporter.api.Credentials credentials = 1;</code>
     */
    private $credentials = null;
    /**
     * Generated from protobuf field <code>string errorGroupName = 2;</code>
     */
    private $errorGroupName = '';
    /**
     * Generated from protobuf field <code>.uegProto.laravelErrorReporter.api.StackReport stackReport = 3;</code>
     */
    private $stackReport = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct customData = 4;</code>
     */
    private $customData = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \UegProto\LaravelErrorReporter\Api\Credentials $credentials
     *     @type string $errorGroupName
     *     @type \UegProto\LaravelErrorReporter\Api\StackReport $stackReport
     *     @type \Google\Protobuf\Struct $customData
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UegProto\LaravelErrorReporter\Error::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.uegProto.laravelErrorReporter.api.Credentials credentials = 1;</code>
     * @return \UegProto\LaravelErrorReporter\Api\Credentials
     */
    public function getCredentials()
    {
        return $this->credentials;
    }

    /**
     * Generated from protobuf field <code>.uegProto.laravelErrorReporter.api.Credentials credentials = 1;</code>
     * @param \UegProto\LaravelErrorReporter\Api\Credentials $var
     * @return $this
     */
    public function setCredentials($var)
    {
        GPBUtil::checkMessage($var, \UegProto\LaravelErrorReporter\Api\Credentials::class);
        $this->credentials = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string errorGroupName = 2;</code>
     * @return string
     */
    public function getErrorGroupName()
    {
        return $this->errorGroupName;
    }

    /**
     * Generated from protobuf field <code>string errorGroupName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorGroupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->errorGroupName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.uegProto.laravelErrorReporter.api.StackReport stackReport = 3;</code>
     * @return \UegProto\LaravelErrorReporter\Api\StackReport
     */
    public function getStackReport()
    {
        return $this->stackReport;
    }

    /**
     * Generated from protobuf field <code>.uegProto.laravelErrorReporter.api.StackReport stackReport = 3;</code>
     * @param \UegProto\LaravelErrorReporter\Api\StackReport $var
     * @return $this
     */
    public function setStackReport($var)
    {
        GPBUtil::checkMessage($var, \UegProto\LaravelErrorReporter\Api\StackReport::class);
        $this->stackReport = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct customData = 4;</code>
     * @return \Google\Protobuf\Struct
     */
    public function getCustomData()
    {
        return $this->customData;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct customData = 4;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setCustomData($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->customData = $var;

        return $this;
    }

}

