<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ueg/api/error/error.proto

namespace Ueg\Api\Error;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>ueg.api.error.Credentials</code>
 */
class Credentials extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string projectKey = 1;</code>
     */
    private $projectKey = '';
    /**
     * Generated from protobuf field <code>string secretKey = 2;</code>
     */
    private $secretKey = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $projectKey
     *     @type string $secretKey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ueg\Api\Error\Error::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string projectKey = 1;</code>
     * @return string
     */
    public function getProjectKey()
    {
        return $this->projectKey;
    }

    /**
     * Generated from protobuf field <code>string projectKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProjectKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->projectKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string secretKey = 2;</code>
     * @return string
     */
    public function getSecretKey()
    {
        return $this->secretKey;
    }

    /**
     * Generated from protobuf field <code>string secretKey = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSecretKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->secretKey = $var;

        return $this;
    }

}

